#!/usr/bin/env node
/**
 * Build script to generate config.js from environment variables
 * Run this before deploying to Vercel
 */

const fs = require('fs');
const path = require('path');

const openrouterKey = process.env.OPENROUTER_KEY;
const serpapiKey = process.env.SERPAPI_KEY;

if (!openrouterKey || !serpapiKey) {
    console.error('❌ ERROR: Missing environment variables!');
    console.error('Please set OPENROUTER_KEY and SERPAPI_KEY');
    process.exit(1);
}

const configContent = `/* ==================== AUTO-GENERATED CONFIG ==================== */
/* This file is generated by build.js from environment variables */
/* DO NOT EDIT - it will be overwritten on the next build */

const API_KEYS = {
    OPENROUTER_KEY: '${openrouterKey}',
    SERPAPI_KEY: '${serpapiKey}'
};
`;

const configPath = path.join(__dirname, 'config.js');
fs.writeFileSync(configPath, configContent);

console.log('✅ config.js generated successfully from environment variables');
